config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :jobs
  
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount SimpleDiscussion::Engine => "/forum"


  devise_for :users
  root to: 'jobs#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id                  :bigint           not null, primary key
#  company_name        :string
#  company_website     :string
#  compensation_range  :string
#  compensation_type   :string
#  estimated_hours     :string
#  featured            :boolean          default(FALSE)
#  featured_until      :datetime
#  headquarters        :string
#  link_to_apply       :string
#  price               :integer
#  published_at        :datetime
#  remote              :boolean          default(FALSE)
#  slug                :string
#  status              :string           default("pending")
#  title               :string
#  upsell_type         :string
#  years_of_experience :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  user_id             :bigint           not null
#
# Indexes
#
#  index_jobs_on_slug     (slug) UNIQUE
#  index_jobs_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Job < ApplicationRecord
  extend FriendlyId

  friendly_id :slug_candidates, use: [:slugged, :finders]

  # Relations
  belongs_to :user
  has_rich_text :description
  has_rich_text :company_description
  has_one_attached :company_logo
  
  # Scopes
  scope :desc, -> { order(created_at: :desc) }
  scope :pending, -> { where(status: JOB_STATUSES[:pending]) }
  scope :published, -> { where(status: JOB_STATUSES[:published]) }
  scope :archived, -> { where(status: JOB_STATUSES[:archived]) }
  # Constants
  COMPENSATION_TYPES = [
    "Contract",
    "Full-time"
  ]

  COMPENSATION_RANGES = [
    "50,000 - 60,000",
    "60,000 - 70,000",
    "70,000 - 80,000",
    "90,000 - 100,000",
    "110,000 - 120,000",
    "120,000 - 130,000",
    "130,000 - 140,000",
    "140,000 - 150,000",
    "150,000 - 160,000",
    "170,000 - 180,000",
    "180,000 - 190,000",
    "190,000 - 200,000",
    "200,000 - 210,000",
    "210,000 - 220,000",
    "210,000 - 220,000",
    "greater than 220,000",


  ].freeze
  
  HOURLY_RANGES = [
    "less than 10",
    "10-30",
    "30-60",
    "60-90",
    "more than 100",
  ].freeze

  JOB_STATUSES = {
    pending: "pending",
    published: "published",
    archived: "archived"
  }.freeze

  YEARS_OF_EXPERIENCE_RANGE = [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "more than 10"
  ].freeze

  def slug_candidates
    [:title, [:title, :company_name]]
  end

  def pending?
    self.status == Job::JOB_STATUSES[:pending]
  end
  def published?
    self.status == Job::JOB_STATUSES[:published]
  end
  def archived?
    self.status == Job::JOB_STATUSES[:archived]
  end

  def should_generate_new_friendly_id?
    if !slug?
      title_changed?
    else
      false
    end
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.published.desc
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @job.user = current_user

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(
        :company_logo,
        :company_name,
        :company_website,
        :company_description,
        :compensation_range,
        :compensation_type,
        :description,
        :estimated_hours,
        :headquarters,
        :link_to_apply,
        :price,
        :remote,
        :role_type,
        :title,
        :upsell_type,
        :years_of_experience,
      )
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<div class="p-10 mb-24 bg-white border rounded">
  <%= form_with(model: job, local: true, multipart: true) do |form| %>
    <% if job.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

        <ul>
          <% job.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="flex flex-wrap items-center justify-between input-group">
      <div>
        <%= form.label :company_logo, class: "label"%>
        <%= form.file_field :company_logo %>
      </div>
      <% if form.object.company_logo.attached? %>
        <%= image_tag form.object.company_logo, class: "w-24 h-auto"%>
      <% end %>
    </div>

    <div class="input-group">
      <%= form.label :title, class: "label"%>
      <%= form.text_field :title, class: "input" %>
    </div>

    <div class="grid grid-cols-1 gap-6 lg:grid-cols-2 input-group">
      <div class="lg:col-span-1">
        <%= form.label :link_to_apply, class: "label"%>
        <%= form.text_field :link_to_apply, class: "input" %>
      </div>

      <div class="lg:col-span-1">
        <%= form.label :headquarters, class: "label"%>
        <%= form.text_field :headquarters, class: "input" %>
      </div>
    </div>

    <div class="input-group">
      <%= form.label :description, class: "label"%>
      <%= form.rich_text_area :description, class: "input" %>
    </div>

    <div class="grid grid-cols-1 gap-6 lg:grid-cols-2 input-group">
      <div class="lg:col-span-1">
        <%= form.label :company_name, class: "label"%>
        <%= form.text_field :company_name, class: "input" %>
      </div>

      <div class="lg:col-span-1">
        <%= form.label :company_website, class: "label"%>
        <%= form.text_field :company_website, class: "input" %>
      </div>
    </div>

    <div class="input-group">
      <%= form.label :company_description, class: "label"%>
      <%= form.rich_text_area :company_description, class: "input" %>
    </div>

    <div class="flex flex-wrap items-center justify-start lg:flex-no-wrap input-group">
      <div class="w-full mb-6 lg:pr-4 lg:w-1/3 lg:mb-0">
        <%= form.label :compensation_type, class: "label" %>
        <div class="relative">
          <%= form.select :compensation_type, Job::COMPENSATION_TYPES,{}, { class: "select" } %>
          <%= select_arrow %>
        </div>
      </div>

      <div class="w-full mb-6 lg:px-2 lg:w-auto lg:mb-0">
        <%= form.label :compensation_range, class: "label"%>
        <%= form.text_field :compensation_range, class: "input" %>
      </div>

      <div class="w-full lg:pl-4 lg:w-auto">
        <%= form.label :estimated_hours, class: "label"%>
        <%= form.text_field :estimated_hours, class: "input" %>
      </div>
    </div>

    <div class="lg:pr-8 lg:w-1/3 input-group lg">
      <%= form.label :years_of_experience, class: "label"%>
      <%= form.text_field :years_of_experience, class: "input" %>
    </div>

    <div class="lg:w-1/2 input-group input-checkbox">
      <%= form.check_box :remote %>
      <%= form.label :remote, "Is this a remote only role?", class: "label"%>
    </div>

    <div class="input-group">
      <%= form.submit  class: "btn btn-green"%>
    </div>
  <% end %>
</div>

app/views/jobs/_job.html.erb
<div class="relative">
  <%= link_to job, class: "border-2 border-black rounded-lg py-6 lg:px-12 px-6 mb-4 block transition ease-in-out duration-300 hover:shadow-lg group" do %>

    <% if job.company_logo.attached? %>
      <div class="absolute top-0 left-0 w-16 h-16 mt-8 -ml-8 transition duration-300 ease-in-out transform rounded-full group-hover:-rotate-5 group-hover:scale-105 hover:shadow-lg">
        <%= image_tag job.company_logo.variant(resize_to_fit: [200, 200]), class: "w-16 h-16 object-cover border border-black rounded-full flex-shrink-0" %>
      </div>
    <% end %>

    <div class="flex items-center">
      <p class="text-gray-700"><%= job.company_name %></p>

      <% if job.featured? %>
        <span class="px-2 py-px ml-2 text-xs font-bold tracking-wide text-black uppercase bg-yellow-500 rounded-lg">Featured</span>
      <% end %>
    </div>

    <h3 class="text-xl font-black"><%= job.title %> </h3>

    <p class="mb-1 text-sm leading-tight text-gray-700">
      <%= job.compensation_type %> <span class="px-px text-gray-600">&bull;</span>
      <% if job.compensation_type.downcase == "contract" %>
        <%= job.estimated_hours %> hours
      <% else %>
        <%= number_to_currency(job.compensation_range) %> <span class="px-px text-gray-600">&bull;</span> <%= pluralize(job.years_of_experience, 'year') %> of experience
      <% end %>
    </p>
    <p class="text-sm leading-tight text-gray-700">
      <% if job.remote? %>
        Remote,
      <% end %>
      <%= job.headquarters %>
    </p>

  <% end %>

  <% if admin? %>
    <div class="absolute top-0 right-0 mt-4 mr-4">
      <%= link_to 'Edit', edit_job_path(job), class: "underline mr-1" %>
      <%= link_to 'Delete', job, method: :delete, data: { confirm: 'Are you sure?' }, class: "underline" %>
    </div>
  <% end %>
</div>

app/views/jobs/edit.html.erb
<div class='max-w-4xl mx-auto'>
    <h1 class='my-4 text-3xl font-black text-center'>Edit your Job <%= @job.title %></h1>
    <%= render 'form', job: @job %>
</div>

app/views/jobs/index.html.erb
<% content_for :hero do %>
  <div class="py-24 mb-16 text-white bg-red-600">
    <div class="container flex flex-wrap justify-center mx-auto text-center">
      <h1 class="text-4xl font-black leading-tight lg:text-6xl">Find a Ruby on Rails developer</h1>
      <p class="w-full text-lg text-red-100">The internet's number one resource for Ruby on Rails developers</p>

      <div class="flex items-center mt-6 mb-3">
        <%= link_to "Find a developer", "#", class: "btn bg-teal-600 hover:bg-teal-500 py-3 px-6 lg:mr-2 shadow-sm border border-teal-500"%>
        <%= link_to "Find a job", jobs_path(anchor: "jobs-index"), class: "btn bg-red-700 lg:ml-2 py-3 px-6 hover:bg-red-600 shadow-sm border border-red-500" %>

      </div>
      <p class="w-full">or find developer friends in the <%= link_to "community", "#", class: "underline" %></p>
    </div>
  </div>
<% end %>

<div id="jobs-index" class="container px-0 mx-auto mb-24 lg:px-48">
  <%= render @jobs %>
</div>

app/views/jobs/new.html.erb
<div data-controller="jobs">
  <div data-target="jobs.mount"></div>
</div>

app/views/jobs/show.html.erb
<div class="container px-4 mx-auto mt-10 mb-24 lg:px-24">

  <div class="flex flex-wrap items-center justify-between border-b lg:border-0">
    <%= link_to root_path, class: "mb-4 inline-flex items-center justify-start group" do %>
      <%= render_svg "icons/chevron-left", styles: "fill-current w-5 h-5 text-red-600 group-hover:text-purple-700" %>
      <p class="text-sm text-red-600 group-hover:text-purple-700">Back to all jobs</p>
    <% end %>
  </div>

  <div class="grid grid-cols-1 gap-16 pt-6 lg:grid-cols-12">
    <div class="lg:col-span-8">
      <%= link_to @job.company_name, @job.company_website, class: "text-base text-gray-600 hover:text-teal-500" %>

      <h1 class="mb-2 text-3xl font-black leading-tight lg:text-4xl"><%= @job.title %></h1>
      <p class="pb-3 mb-3 leading-tight text-gray-700">
        <%= @job.compensation_type %> <span class="px-px text-gray-600">&bull;</span>
        <% if @job.compensation_type.downcase == "contract" %>
          <%= @job.estimated_hours %> hours
        <% else %>
          <%= number_to_currency(@job.compensation_range) %> <span class="px-px text-gray-600">&bull;</span> <%= pluralize(@job.years_of_experience, 'year') %> of experience
        <% end %>
      </p>

      <h3 class="mb-2 text-xs font-bold tracking-wider text-gray-800 uppercase">About the role</h3>
      <div class="prose">
        <%= @job.description %>
      </div>

      <h3 class="mt-10 mb-2 text-xs font-bold tracking-wider text-gray-800 uppercase">About the company</h3>
      <div class="mb-6 prose">
        <%= @job.company_description %>
      </div>

      <%= link_to "Apply for this role", @job.link_to_apply, class: "btn btn-red px-10 py-3" %>

      <% if author_of(@job) || admin? %>
        <%= link_to 'Edit this job', edit_job_path(@job), class: "ml-2 block mt-6" %>
      <% end %>
    </div>
    <div class="mb-10 text-center lg:col-span-4">
      <div class="sticky top-0 p-6 mt-6 text-gray-700 bg-white border-2 border-black rounded-lg shadow-sm">
        <% if @job.company_logo.attached? %>
          <div class="flex justify-center">
            <div class="w-16 h-16 my-3 text-center">
              <%= image_tag @job.company_logo.variant(resize_to_fit: [200, 200]), class: "flex-shrink-0 rounded-full object-cover object-center w-full h-16 border border-black" %>
            </div>
          </div>
        <% end %>
        <p><%= link_to @job.company_name, @job.company_website, class: "text-base text-gray-600 hover:text-teal-500"%></p>
        <p class="mb-2 text-xl font-black leading-tight text-gray-800 lg:px-4"><%= @job.title %></p>
        <p class="pb-3 mb-3 text-sm leading-tight text-gray-700">
          <%= @job.compensation_type %> <span class="px-px text-gray-600">&bull;</span>
          <% if @job.compensation_type.downcase == "contract" %>
            <%= @job.estimated_hours %> hours </br>
        <% else %>
          <%= number_to_currency(@job.compensation_range) %> </br> <%= pluralize(@job.years_of_experience, 'year') %> of experience
      <% end %>
    </p>
    <%= link_to "Apply for this role", @job.link_to_apply, class: "btn btn-red px-10 py-3" %>
  </div>
</div>
</div>
</div>