config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :jobs
  
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount SimpleDiscussion::Engine => "/forum"


  devise_for :users
  root to: 'jobs#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flash_notice.html.erb
<% flash.each do |type, message| %>
  <% if type == "alert" %>
    <div class="bg-red-500">
      <div class="container px-2 py-4 mx-auto font-sans font-medium text-center text-white"><%= message %></div>
    </div>
  <% end %>
  <% if type == "notice" %>
    <div class="bg-green-500">
      <div class="container px-2 py-4 mx-auto font-sans font-medium text-center text-white"><%= message %></div>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="py-5 bg-red-700 text-center text-white">
        Made By <a href="https://github.com/Dfsma" class="hover:text-purple-700">Diego<a> 😎 &copy 2020
</footer>

app/views/shared/_head.html.erb
 <head>
  <title>
    <% if content_for?(:title) %>
      <%= yield :title %> |
    <% end %>
    railsdev.com
  </title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <%= stylesheet_link_tag  "https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap", media: 'all', 'data-turbolinks-track': 'reload'  %>
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'https://js.stripe.com/v3/', 'data-turbolinks-track': 'reload' %>
</head>

app/views/shared/_header.html.erb
<header>
  <nav class="flex flex-wrap items-center justify-between px-3 py-3 text-gray-700 lg:px-10">
    <%= render "shared/left_nav" %>
    <%= render "shared/right_nav" %>
  </nav>
</header>

app/views/shared/_left_nav.html.erb
<div class="flex items-center mr-6 flex-no-shrink">
  <%= link_to root_path, class:"link text-lg tracking-tight font-semibold group text-red-600 hover:text-red-700 transition ease-in-out flex items-center justify-start" do %>
    <%= render_svg "icons/railsdevs-mark", title: "railsdevs.com", styles: "fill-current w-8 h-8 text-red-600 group-hover:text-red-700" %>
    <span class="ml-2 text-lg font-black text-black">RailsDevs</span>
  <% end %>
</div>
<div class="block lg:hidden">
  <button class="flex items-center px-3 py-2 border border-gray-500 rounded text-grey hover:text-gray-600 hover:border-gray-600">
    <svg class="w-3 h-3 fill-current" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
  </button>
</div>

app/views/shared/_right_nav.html.erb
<div class="items-center block w-full text-center lg:flex-1 lg:flex lg:text-left">
  <div class="lg:flex-grow"></div>
  <div class="items-center block w-full mt-2 text-center lg:flex lg:flex-row lg:flex-1 lg:mt-0 lg:text-left lg:justify-end">


    <% if user_signed_in? %>
      <%= link_to "Edit account", edit_user_registration_path, class: "btn btn-transparent mr-2" %>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"btn btn-transparent" %>
    <% else %>
      <%= link_to "Login", new_user_session_path, class:"btn btn-transparent mr-2" %>
      <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-transparent" %>
    <% end %>

    <span class="px-2 text-gray-400">|</span>

    <%= link_to "Find jobs", jobs_path, class: "btn btn-transparent mr-2" %>
    <%= link_to "Post a job", new_job_path, class: "btn btn-teal" %>
  </div>
</div>

app/views/shared/_select_arrow.html.erb
  
<div class="absolute inset-y-0 right-0 flex items-center px-2 text-gray-700 pointer-events-none">
  <svg class="w-4 h-4 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
</div>

app/views/shared/_spacer.html.erb
<hr/>